title: Jingwei Zhang's Homepage
page-top-title: Jingwei Zhang
top-section-bg-text: Electronic & Information Engineering
home-subtitle: Jingwei Zhang&ensp;|&ensp;张荆玮
copyright-text: '&copy; Jingwei Zhang 2023-2026. All Rights Reserved.'
